"""Agregado Documento a la tabla de libro venta

Revision ID: 05fb03505b00
Revises: f8c1c79792e0
Create Date: 2025-05-24 15:33:12.658212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fb03505b00'
down_revision = 'f8c1c79792e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro_ventas', schema=None) as batch_op:
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
