"""agregar id_cliente a retenciones

Revision ID: 70d1a4acfb72
Revises: a29c53456b4b
Create Date: 2025-06-02 23:53:34.425237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d1a4acfb72'
down_revision = 'a29c53456b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retenciones_compras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cliente'))
        batch_op.drop_index(batch_op.f('idx_factura'))
        batch_op.drop_index(batch_op.f('idx_fecha_emision'))
        batch_op.drop_index(batch_op.f('idx_fecha_registro'))
        batch_op.drop_constraint(batch_op.f('retenciones_compras_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('retenciones_compras_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['id_cliente'], ['id_cliente'])
        batch_op.create_foreign_key(None, 'libro_compras', ['idfacturacompra'], ['idfacturacompra'])

    with op.batch_alter_table('retenciones_ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cliente'))
        batch_op.drop_index(batch_op.f('idx_factura'))
        batch_op.drop_index(batch_op.f('idx_fecha_emision'))
        batch_op.drop_index(batch_op.f('idx_fecha_registro'))
        batch_op.drop_constraint(batch_op.f('retenciones_ventas_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('retenciones_ventas_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'libro_ventas', ['idfacturaventa'], ['idfacturaventa'])
        batch_op.create_foreign_key(None, 'clientes', ['id_cliente'], ['id_cliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retenciones_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('retenciones_ventas_ibfk_2'), 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('retenciones_ventas_ibfk_1'), 'libro_ventas', ['idfacturaventa'], ['idfacturaventa'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_emision'), ['fecha_emision'], unique=False)
        batch_op.create_index(batch_op.f('idx_factura'), ['idfacturaventa'], unique=False)
        batch_op.create_index(batch_op.f('idx_cliente'), ['id_cliente'], unique=False)

    with op.batch_alter_table('retenciones_compras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('retenciones_compras_ibfk_1'), 'libro_compras', ['idfacturacompra'], ['idfacturacompra'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('retenciones_compras_ibfk_2'), 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_emision'), ['fecha_emision'], unique=False)
        batch_op.create_index(batch_op.f('idx_factura'), ['idfacturacompra'], unique=False)
        batch_op.create_index(batch_op.f('idx_cliente'), ['id_cliente'], unique=False)

    # ### end Alembic commands ###
