"""Initial migration

Revision ID: 8146bfc15b7a
Revises: 
Create Date: 2025-05-24 01:54:05.105603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8146bfc15b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('representante', sa.String(length=100), nullable=True),
    sa.Column('rif', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('contribuyente', sa.Boolean(), nullable=True),
    sa.Column('registradora', sa.String(length=50), nullable=True),
    sa.Column('clasificacion', sa.String(length=50), nullable=True),
    sa.Column('usuarioseniat', sa.String(length=50), nullable=True),
    sa.Column('claveseniat', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('activo', 'inactivo', name='statusenum'), nullable=True),
    sa.Column('clavepatente', sa.String(length=50), nullable=True),
    sa.Column('directoriocomo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('libro_compras',
    sa.Column('idfacturacompra', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('numerofactura', sa.String(length=50), nullable=False),
    sa.Column('control', sa.String(length=50), nullable=True),
    sa.Column('fechar', sa.Date(), nullable=False),
    sa.Column('fechafactura', sa.Date(), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=100), nullable=False),
    sa.Column('montoTotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exentas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('facturapolar', sa.Boolean(), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('idfacturacompra')
    )
    op.create_table('libro_ventas',
    sa.Column('idfacturaventa', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('numerofactura', sa.String(length=50), nullable=False),
    sa.Column('fechar', sa.Date(), nullable=False),
    sa.Column('fechafactura', sa.Date(), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('montoTotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exentas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cajaregistradora', sa.String(length=50), nullable=True),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('idfacturaventa'),
    sa.UniqueConstraint('numerofactura')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('admin', 'usuario', 'editor'),
               type_=sa.Enum('admin', 'editor', 'ver'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.Enum('admin', 'editor', 'ver'),
               type_=mysql.ENUM('admin', 'usuario', 'editor'),
               existing_nullable=False)

    op.drop_table('libro_ventas')
    op.drop_table('libro_compras')
    op.drop_table('clientes')
    # ### end Alembic commands ###
