"""Cambio contribuyente a enum ordinario/especial

Revision ID: f8c1c79792e0
Revises: 8146bfc15b7a
Create Date: 2025-05-24 03:43:24.724917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8c1c79792e0'
down_revision = '8146bfc15b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('contribuyente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('ordinario', 'especial', name='tipo_contribuyente'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('contribuyente',
               existing_type=sa.Enum('ordinario', 'especial', name='tipo_contribuyente'),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
